# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

console_title_template: "{{.Folder}}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
      folder_separator_icon: <transparent>  </>
      style: agnoster_full
    leading_diamond: █
    trailing_diamond: 
    template: "{{if .Root}}⛧︀{{else}}{{end}} {{ .Path }} "
    foreground: "#fefaea"
    background: "#23513c"
    type: path
    style: diamond
  - properties:
      branch_icon: "\ueb00 "
      cache_duration: none
      fetch_stash_count: true
      fetch_status: true
    trailing_diamond: 
    template: " {{ if ne .Env.TERM_PROGRAM \"vscode\" }}{{ .HEAD }}{{  if .Staging.Changed }} \uf046 {{ .Staging.String }}</>{{ end }}{{  if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{  if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{  if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }}{{end}} "
    foreground: "#0e0b06"
    background: "#678d58"
    type: git
    style: diamond
    background_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}#f7e2b2{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ffcc80{{ end }}"
    - "{{ if gt .Ahead 0 }}#b388ff{{ end }}"
    - "{{ if gt .Behind 0 }}#b388ff{{ end }}"
  - properties:
      cache_duration: none
      style: dallas
    trailing_diamond: 
    template: " \ueba2 {{ .FormattedMs }}s "
    foreground: "#fefaea"
    background: "#427aa1"
    type: executiontime
    style: diamond
  - properties:
      cache_duration: none
    trailing_diamond: 
    template: " {{ reason .Code }} "
    foreground: "#fefaea"
    background: "#9d400b"
    type: status
    style: diamond
- type: prompt
  alignment: right
  segments:
  - properties:
      cache_duration: none
    leading_diamond: 
    template: " {{ if ne .Env.TERM_PROGRAM \"vscode\" }}\ue77f {{ .Full }}{{end}} "
    foreground: "#fefaea"
    background: "#512bd4"
    type: dotnet
    style: diamond
  - properties:
      cache_duration: none
    leading_diamond: 
    template: " {{ if ne .Env.TERM_PROGRAM \"vscode\" }}\ue718 {{ .Full }}{{end}} "
    foreground: "#fefaea"
    background: "#5fa04e"
    type: node
    style: diamond
  - properties:
      cache_duration: none
    leading_diamond: 
    foreground: "#ca0000"
    background: "#fefaea"
    type: npm
    style: diamond
  - properties:
      cache_duration: none
    leading_diamond: 
    template: " {{ if ne .Env.TERM_PROGRAM \"vscode\" }}\ue7a8 {{ .Full }}{{end}} "
    foreground: "#0e0b06"
    background: "#99908a"
    type: rust
    style: diamond
  - properties:
      cache_duration: none
    leading_diamond: 
    template: " {{ if ne .Env.TERM_PROGRAM \"vscode\" }}\ue620{{end}} "
    foreground: "#fefaea"
    background: "#02027d"
    type: lua
    style: diamond
  - properties:
      cache_duration: none
    leading_diamond: 
    template: " {{ if ne .Env.TERM_PROGRAM \"vscode\" }}{{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }}\uf487 {{.Version}}{{ end }}{{ end }}{{ end }} "
    foreground: "#0e0b06"
    background: "#FBE1C6"
    type: project
    style: diamond
  - properties:
      cache_duration: none
      time_format:  15:04:05
    leading_diamond: 
    template: " {{ if ne .Env.TERM_PROGRAM \"vscode\" }}{{ .CurrentDate | date .Format }}{{end}} "
    foreground: "#0e0b06"
    background: "#f5bb7d"
    type: time
    style: diamond
  - properties:
      cache_duration: none
      time_format:  2006-01-02
    leading_diamond: 
    trailing_diamond: █
    template: " {{ if ne .Env.TERM_PROGRAM \"vscode\" }}{{ .CurrentDate | date .Format }}{{end}}"
    foreground: "#0e0b06"
    background: "#bc6c25"
    type: time
    style: diamond
- type: prompt
  alignment: left
  segments:
  - properties:
      always_enabled: true
      cache_duration: none
    template: "\uf054 "
    foreground: "#678d58"
    type: status
  newline: true
version: 3
