blocks:
  - alignment: left
    type: prompt
    segments:
      - background: '#01579b'
        foreground: '#ffffff'
        leading_diamond: '<transparent,#01579b></>'
        properties:
          folder_separator_icon: '<transparent>  </>'
          style: agnoster_full
        style: diamond
        template: ' {{ .Path }} '
        type: path

      - background: '#00C853'
        background_templates:
          - '{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb3b{{ end }}'
          - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ffcc80{{ end }}'
          - '{{ if gt .Ahead 0 }}#b388ff{{ end }}'
          - '{{ if gt .Behind 0 }}#b388ff{{ end }}'
        foreground: '#000000'
        powerline_symbol: 
        properties:
          fetch_stash_count: true
          fetch_status: true
        style: powerline
        template: ' {{ .HEAD }}{{
          if .Staging.Changed }}<#FF6F00>  {{ .Staging.String }}</>{{ end }}{{
          if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{
          if .Working.Changed }}  {{ .Working.String }}{{ end }}{{
          if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
        type: git

      - type: docker
        style: powerline
        powerline_symbol: 
        foreground: '#000000'
        background: '#0b59e7'
        template: '  {{ .Context }} '
      - type: dotnet
        style: powerline
        powerline_symbol: 
        foreground: '#000000'
        background: '#00ffff'
        template: '  '
      - type: node
        style: powerline
        powerline_symbol: 
        background: '#000000'
        foreground: '#45bf17'
        template: '  '
      - type: rust
        style: powerline
        powerline_symbol: 
        foreground: '#193549'
        background: '#99908a'
        template: '  '
      - type: lua
        style: powerline
        powerline_symbol: 
        foreground: white
        background: blue
        template: '  '
      - type: npm
        style: powerline
        powerline_symbol: 
        background: '#000000'
        foreground: '#fe4a49'
        template: '  '
      - type: project
        style: powerline
        powerline_symbol: 
        foreground: '#193549'
        background: '#ffeb3b'
        template: ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }} {{.Version}}{{ end }} {{ if .Name }}{{ .Name }}{{ end }}{{ end }} '

      - background: '#910000'
        foreground: '#ffffff'
        powerline_symbol: 
        style: powerline
        template: '<transparent></> {{ reason .Code }} '
        type: status

  - alignment: right
    type: prompt
    segments:
      - type: executiontime
        properties:
          style: dallas
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: ' {{ .FormattedMs }}s'
        background: '#5ab5fb'
        foreground: '#fff'

      - type: time
        properties:
          time_format: "\ue641 15:04:05"
        template: '{{ .CurrentDate | date .Format }} '
        leading_diamond: ' '
        style: diamond
        background: '#407faf'
        foreground: '#fff'

      - type: time
        properties:
          time_format: "\uf073 2006-01-02"
        template: ' {{ .CurrentDate | date .Format }}'
        leading_diamond: "\ue0ba"
        trailing_diamond: 
        style: diamond
        background: '#244762'
        foreground: '#fff'

  - alignment: left
    newline: true
    segments:
      - foreground: '#ffffff'
        foreground_templates:
          - '{{ if gt .Code 0 }}#ff0000{{ end }}'
        properties:
          always_enabled: true
        style: plain
        template: '❯ '
        type: status
    type: prompt

console_title_template: '{{if .Root}} ⚡ {{end}}{{.Folder}}'
version: 2
