blocks:
  - alignment: left
    type: prompt
    segments:
      - type: path
        properties:
          folder_separator_icon: '<transparent>  </>'
          style: agnoster_full
          home_icon: 󰚡
        template: ' {{ .Path }} '
        style: diamond
        leading_diamond: '<transparent>'
        trailing_diamond: 
        background: '#78B5EE'
        foreground: '#23282b'

      - type: git
        properties:
          fetch_stash_count: true
          branch_icon: ' '
          fetch_status: true
        template: ' {{ .HEAD }}{{
          if .Staging.Changed }}<#23282b>  {{ .Staging.String }}</>{{ end }}{{
          if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{
          if .Working.Changed }}  {{ .Working.String }}{{ end }}{{
          if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
        background_templates:
          - '{{ if or (.Working.Changed) (.Staging.Changed) }}#f7e2b2{{ end }}'
          - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ffcc80{{ end }}'
          - '{{ if gt .Ahead 0 }}#b388ff{{ end }}'
          - '{{ if gt .Behind 0 }}#b388ff{{ end }}'
        style: diamond
        trailing_diamond: 
        background: '#00c853'
        foreground: '#23282b'

      - background: '#910000'
        foreground: '#ECEDEA'
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: ' 󰯆 {{ reason .Code }} '
        type: status

  - alignment: right
    type: prompt
    segments:
      - type: executiontime
        properties:
          style: dallas
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: '  {{ .FormattedMs }}s '
        background: '#D9B0D6'
        foreground: '#23282b'

      - type: dotnet
        style: diamond
        leading_diamond: 
        foreground: '#ECEDEA'
        background: '#512bd4'
        template: '  {{ .Full }} '
      - type: node
        style: diamond
        leading_diamond: 
        background: '#5fa04e'
        foreground: "#ECEDEA"
        template: '  {{ .Full }} '
      - type: npm
        style: diamond
        leading_diamond: 
        background: "#ECEDEA"
        foreground: "#ca0000"
      - type: rust
        style: diamond
        leading_diamond: 
        foreground: '#193549'
        background: '#99908a'
        template: '  '
      - type: lua
        template: '  '
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        foreground: '#ECEDEA'
        background: blue

      - type: project
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        foreground: '#193549'
        background: '#ffeb3b'
        template: ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }} {{.Version}}{{ end }}{{ if .Name }}{{ if not .Version }}󰣙 {{ end }}{{ .Name }}{{ end }}{{ end }} '

      - type: time
        properties:
          time_format: "\ue641 15:04:05"
        template: ' {{ .CurrentDate | date .Format }} '
        style: diamond
        leading_diamond: 
        background: '#4D8EC4'
        foreground: '#23282b'

      - type: time
        properties:
          time_format: "\uf073 2006-01-02"
        template: ' {{ .CurrentDate | date .Format }} '
        style: diamond
        leading_diamond: 
        trailing_diamond: '<transparent>'
        background: '#748EB7'
        foreground: '#23282b'

  - alignment: left
    newline: true
    segments:
      - type: status
        properties:
          always_enabled: true
        template: "{{if .Root}} {{else}}󰘧 {{end}}"
        foreground_templates:
          - '{{ if gt .Code 0 }}#ff0000{{ end }}'
        foreground: '#748EB7'

    type: prompt

console_title_template: '{{.Folder}}'

version: 2
